## env file
name: test-environment
on: workflow_dispatch
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=branchName::${GITHUB_REF#refs/*/}

      - name: Check output
        run: |
              echo ${{ steps.vars.outputs.branchName }}
              echo "RELEASE_BRANCH=${{ steps.vars.outputs.short_ref }}" >> $GITHUB_ENV         
        
      - name: Set env to DEV
        run: echo $GITHUB_ENV

